#!/usr/bin/env bash
#display usage

usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -lt 4 ]; then
  usage
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_keys="$4"

export SCP_OPTS="-o StrictHostKeyChecking=no"

scp $SCP_OPTS -i "$ssh_key" "$file_path" "$username@server_ip:~/"

if [ "$?" -eq 0]; then
  echo "Success"
else
  echo "Failure"
fi
