#!/usr/bin/env bash
#install nginx server

sudo apt update

sudo apt install -y nginx

sudo service nginx start

echo "<html><head><title>Hello World</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html

nginx_status=$(sudo service nginx status)

if [[ $nginx_status == *"active (running)"* ]] && sudo netstat -tuln | grep ":80 "; then
  echo "Nginx is running."
else
  echo "Nginx failed."
fi
