#!/usr/bin/env bash
#install nginx with configurations

sudo apt-get install -y nginx
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Helloo World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "No page found" > /var/www/html/404.html

printf %s "server{
  listen 80 default_server;
  listen [::]:80 default_server;
  add_header X-Served-By $hostname;
  root /var/www/html;
  index index.html index htm;

  location /redirect_me{
     return 301 http://facebook.com/;
  }

  error_page 404 /404.html;
  location /404{
   root /var/www/html;
   internal;
  }
}" > /etc/nginx/sites-available/default

service nginx restart
