#!/usr/bin/env bash
#install configurations

sudo apt-get install -y haproxy

echo "ENABLED-1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cgf{,.orignal}
touch /etc/haproxy/haproxy.cfg

printf %s "global
        log 127.0.0.1 local0 notice
        maxconn 2000
        user haproxy
        group haproxy

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option  redispatch
        timeout connect 5000
        timeout client  30000
        timeout server  30000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 400 /etc/haproxy/errors/403.http
        errorfile 400 /etc/haproxy/errors/408.http
        errorfile 400 /etc/haproxy/errors/500.http
        errorfile 400 /etc/haproxy/errors/502.http
        errorfile 400 /etc/haproxy/errors/503.http
        errorfile 400 /etc/haproxy/errors/504.http

frontend http-in
        timeout client  30000
        bind 0:80
        default_backend servers

backend servers
        timeout connect 3000
        timeout server  30000
        balance roundrobin
        server 399091-web-01 35.153.66.200:80 check
        server 399091-web-02 18.207.140.68:80 check

" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
