#!/usr/bin/env bash
#fix server that won't shut off
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-availbale/default
service nginx stop
pkill nginx
service nginx start
