#!/usr/bin/ env bash
#scrcipt to fix nginx server that won't shut off
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx start
